# Generated by Django 4.2.6 on 2023-10-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='case_number',
            new_name='CASE_NUMBER',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='emploter_phone_ext',
            new_name='WILLFUL_VIOLATOR',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='agent_attorney_city',
            new_name='WORKSITE_POSTAL_CODE',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='agent_attorney_name',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='agent_attorney_state',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='case_status',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='case_submitted',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_address',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_city',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_country',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_phone',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_postal_code',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_province',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employer_state',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='employment_start_date',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='fulltime_position',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='h_1b_dependent',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='naic_code',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='original_cert_data',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='prevailing_wage',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='pw_source_other',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='pw_unit_of_pay',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='pw_wage_source',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='soc_code',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='soc_name',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='total_workers',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='visa_class',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='wage_rate_of_pay_from',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='wage_rate_of_pay_to',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='wage_unit_of_pay',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='wilful_voilator',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='worksite_city',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='worksite_county',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='worksite_postal_code',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='worksite_state',
        ),
        migrations.AddField(
            model_name='table1',
            name='AGENT_ATTORNEY_CITY',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_PHONE_EXT',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='FULL_TIME_POSITION',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='ORIGINAL_CERT_DATE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='AGENT_ATTORNEY_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='AGENT_ATTORNEY_STATE',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='CASE_STATUS',
            field=models.CharField(choices=[('CERTIFIED-WITHDRAWN', 'CERTIFIED-WITHDRAWN'), ('WITHDRAWN', 'WITHDRAWN'), ('CERTIFIED', 'CERTIFIED'), ('DENIED', 'DENIED')], max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='CASE_SUBMITTED',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='DECISION_DATE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_ADDRESS',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_CITY',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_COUNTRY',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_NAME',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_PHONE',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_POSTAL_CODE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_PROVINCE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYER_STATE',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYMENT_END_DATE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='EMPLOYMENT_START_DATE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='H_1B_DEPENDENT',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='JOB_TITLE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='NAIC_CODE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='PREVAILING_WAGE',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='PW_SOURCE_OTHER',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='PW_UNIT_OF_PAY',
            field=models.CharField(choices=[('Year', 'Year'), ('Bi-Weekly', 'Bi-Weekly'), ('Month', 'Month'), ('Hour', 'Hour'), ('Month', 'Month')], null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='PW_WAGE_SOURCE',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='SOC_CODE',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='SOC_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='TOTAL_WORKERS',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='VISA_CLASS',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WAGE_RATE_OF_PAY_FROM',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WAGE_RATE_OF_PAY_TO',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WAGE_UNIT_OF_PAY',
            field=models.CharField(choices=[('Year', 'Year'), ('Bi-Weekly', 'Bi-Weekly'), ('Month', 'Month'), ('Hour', 'Hour'), ('Month', 'Month')], null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WORKSITE_CITY',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WORKSITE_COUNTY',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='WORKSITE_STATE',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
