# Generated by Django 4.2.6 on 2023-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_table1_agent_attorney_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='VISA_CLASS',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
