# Generated by Django 4.2.6 on 2023-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_table1_visa_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='TOTAL_WORKERS',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
