# Generated by Django 4.2.6 on 2023-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_table1_total_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='EMPLOYER_CITY',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
